### ISSUE TITLE
Feature Request: Subset genes when comparing 2 experiments

### ISSUE THREAD

**Issue by stephenwood1** [dsurujon/ShinyOmics#8]
Add the ability to select a subset of entered genes when comparing 2 experiments. Output would show all genes, however the subsetted genes would be highlighted in a color or with a larger marker to show how they change over the time points.

**Comment by dsurujon** [comment]
I added a gene selector text box. Currently it works by ONLY showing the specified genes (omitting all other genes). But we should have the option to just highlight the selected genes (with other genes still included).
